### PR TITLE
fix(GRA-1201): remove "local network"

### PR DESCRIPTION
**Pull request by Aceix**
TESTING STEPS:
1. Go to create/read/edit network and node, check that "is local network" or "local range" does not exist

### CODE REVIEW

**Review by 0xdcarns — CHANGES_REQUESTED** [review]
fix conflicts, also will wait on pairing with backend to merge

**Comment by theguy951357** [comment]
I ran this branch a few times and did a shift reload and I cannot get the local range to leave in the node details.

Screenshot 2023-02-24 at 2 56 24 PM

**Comment by Aceix** [comment]
updated

**Review by theguy951357 — APPROVED** [review]
local range and islocalnetwork is gone
no new Ui bugs
pass

**Pull request merged**
